spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}
logging.level.org.springframework.batch: DEBUG

#추가 설정
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    properties:
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springboot
      username: junseong
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
  jpa:
    generate-dll: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: ${chunkSize:1000}

